import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Micro Player";
    width: 400px;
    height: 200px;
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Reproducir";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
